### PR TITLE
JSON sink

### PR DESCRIPTION
**Pull request by kevingessner**

### CODE REVIEW

**Comment by timothysc** [comment]
@kevingessner Does this meet your needs ? https://github.com/heptio/eventrouter/pull/5/files , seems like I addressed that yesterday.

**Comment by kevingessner** [comment]
Hey @timothysc -- that change doesn't quite.  I'm using filebeat to ship these logs to logstash, and the newlines in the output mean I can't get it to reliably detect a complete event.  The mixture of text and JSON also makes parsing in logstash a bit of a chore.  I think embedding it all into JSON solves both of those.

**Comment by timothysc** [comment]
Ah, let me meld the two then.

**Comment by timothysc** [comment]
I'll merge this one, then redux it into glog, b/c they serve the same purpose.

**Comment by kevingessner** [comment]
Thanks @timothysc !

**Pull request merged**
